MyWeb/MyBlog/urls.py
from django.urls import path
from . import views



app_name = "MyBlog"
urlpatterns = [
    
    path("",views.article_list,name="home"),
    path("article/<int:pk>/",views.commentview,name="article_detail"),
    path("archive/tag/<slug:tag_slug>/",views.ArriveAtView.as_view(),name="arrived-by-tag"),
    path("archive/category/<slug:cat_slug>/",views.ArriveAtView.as_view(),name="arrived-by-category"),
    path("archive/",views.ArchiveView.as_view(),name="archive"),
    path('about/<slug:slug>/', views.AboutDetailView.as_view(), name='about'),
    path("search/",views.SearchView.as_view(),name="search"),

    
    
]

MyWeb/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from debug_toolbar.toolbar import debug_toolbar_urls
# --------------------解决生产环境下static文件无法加载
from django.contrib.staticfiles.views import serve
from django.urls import re_path

def return_static(request,path,insecure=True,**kwargs):
    return serve(request,path,insecure,**kwargs)
# ----------------------------

urlpatterns = [
    path('markdownx/', include('markdownx.urls')),
    path("MyBlog/",include("MyBlog.urls")),

    path("admin/", admin.site.urls),
    
    re_path(r"^static/(?P<path>.*)$",return_static,name='static')#生产环境
] + debug_toolbar_urls()

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWeb/MyBlog/models.py
from django.db import models
from django.db.models import F
from markdownx.models import MarkdownxField
import markdown
import bleach
from PIL import Image
from django.utils import timezone
from MyBlog.utils.ip_utils import get_client_ip


class Category(models.Model):
    """ 分类 """
    name = models.CharField(max_length=100,unique=True)
    
    slug = models.SlugField(max_length=100,unique=True)

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = "文章分类"

    def __str__(self):
        return self.name
    
class ArticleTag(models.Model):
    """ 标签 """
    name = models.CharField(max_length=100,unique=True)
    
    slug = models.SlugField(max_length=100,unique=True)
        
    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = "文章标签"

    def __str__(self):
        return self.name

class Article(models.Model):
    """ 文章 """
    # 标题概述
    title = models.CharField(max_length=200)
    overview = models.TextField(max_length=300,default='',blank=True,verbose_name="概述")

    # 分类标签
    category = models.ForeignKey(Category,null=True,blank=True,on_delete=models.SET_NULL,verbose_name="分类",related_name='article')
    tags = models.ManyToManyField(ArticleTag,blank=True,verbose_name="标签")

    # 文章内容
    raw_content = MarkdownxField(verbose_name="Markdown原始内容")
    rendered_content = models.TextField(verbose_name="渲染后的html",editable=False)
    version = models.PositiveIntegerField(default=1)
    
    # 发布更新时间。
    pub_date = models.DateTimeField("发布时间",auto_now_add=True)
    last_updated = models.DateTimeField("最后更新", auto_now=True)

    # 统计
    word_count = models.PositiveIntegerField(default=0,verbose_name="字数",editable=False)
    visited_num = models.PositiveIntegerField(default=0,verbose_name="访问量",editable=False)
    
    cover_img = models.ImageField(upload_to="article_cover/",null=True,blank=True,verbose_name="文章封面")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = "文章"
        ordering = ['-pub_date']

    def increase_visited(self,request=None):
        """ 访问量增加 """
        
        if request is None:
            Article.objects.filter(pk=self.pk).update(visited_num=F("visited_num")+1)
            self.refresh_from_db(fields=['visited_num'])
            return
        
        ip = get_client_ip(request)
        exclude_ip = ['127.0.0.1','124.79.161.138']
        
        if ip not in exclude_ip:
            Article.objects.filter(pk=self.pk).update(visited_num=F("visited_num")+1)
            self.refresh_from_db(fields=['visited_num'])

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """ 计数 """
        CNwords = sum(1 for char in self.raw_content if '\u4e00' <= char <= '\u9fff')
        NonCNwords = [word for word in self.raw_content.split() if not any('\u4e00' <= char <= '\u9fff' for char in word)]
        self.word_count = CNwords + len(NonCNwords)

        """
            Markdown转换:
                --存储与展示分离:
                    1.原始内容:保留易编辑的Markdown格式(适合后台管理)
                    2.渲染内容:生成可直接展示的HTML(提升前端性能)
        """
        if not self.pk or Article.objects.get(pk=self.pk).raw_content != self.raw_content:
            html = markdown.markdown(self.raw_content, 
                    extensions=[
                    'extra',       
                    #'toc',目录
                    'codehilite',   
                    ],
                    extension_configs={
                        'codehilite':{ 'linenums':None, 'use_pygments': True }
                    }
                )
            
            """
                HTML净化:
                    1.防御XSS攻击:防止用户插入恶意脚本
                    2.内容可控性:限制允许的HTML标签和属性
            """
            self.rendered_content = bleach.clean(
                    html,  
                    # 白名单标签
                    tags=[
                        'p', 'h1', 'h2', 'h3','h4','h5','h6',      
                        'ul', 'li', 'ol',            
                        'pre', 'code', 'blockquote',         
                        'blockquote',           
                        'img', 'a', 'strong', 'em',
                        'table', 'thead', 'tbody', 'tr', 'th', 'td',                 
                        'div','span',
                    ],
                    # 允许的属性
                    attributes={
                        'img': [
                            'src',    
                            'alt',    
                            'title'  
                        ],
                        'a': ['href', 'title', 'rel'],
                        'code': ['class'],
                        'pre': ['class'],
                        'div': ['class', 'id', 'style'],
                        'span': ['class'],
                    }
                )
        
            if self.pk:
                self.version +=1

        super().save(*args, **kwargs)

class Comment(models.Model):
    """
        评论
    """
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="关联文章",related_name="comments")
    comment_date = models.DateTimeField("评论时间", auto_now_add=True,null=True, blank=True )
    body = models.CharField(max_length=500,default='',verbose_name="评论内容")
    author = models.CharField(max_length=100,default="匿名用户",verbose_name="用户")
    email = models.EmailField(verbose_name='邮箱(不会公开)', blank=True)
    #审核状态
    #is_approved = models.BooleanField(default=False,verbose_name="审核通过")

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = "评论"
        ordering = ['-comment_date']

    def __str__(self):
        return f"{self.author}的评论：{self.body[:20]}"
    
    def save(self, *args, **kwargs):
        """确保新评论有创建时间"""
        if not self.pk and not self.comment_date:  
            self.comment_date = timezone.now()
        super().save(*args, **kwargs)

class About(models.Model):
    """关于"""
    title = models.CharField(max_length=200,default="关于我们")
    content = models.TextField(verbose_name="内容")
    slug = models.SlugField(unique=True, default='about-page')

    def __str__(self):
        return self.title
    
class VisitRecord(models.Model):
    " 访问记录 "
    ip_address = models.GenericIPAddressField(verbose_name="IP地址")
    user_agent = models.TextField(verbose_name="用户代理",max_length=500,blank=True,null=True)
    visited_time = models.DateTimeField(verbose_name="访问时间",auto_now_add=True)
    visited_path = models.CharField(verbose_name="访问路径",max_length=200)
    session_id = models.CharField(verbose_name="会话ID",max_length=40,blank=True,null=True)
    is_unique_today = models.BooleanField(verbose_name="今日唯一时间",default=False)

    class Meta:
        verbose_name = "访问记录"
        verbose_name_plural = "访问记录"
        indexes = [
            models.Index(fields=['ip_address','visited_time']),
            models.Index(fields=['session_id','visited_time']),
            models.Index(fields=['visited_time']),
        ]

    
class VisitSummary(models.Model):
    " 访问统计 "
    date = models.DateField(unique=True, verbose_name="日期")
    total_visits = models.IntegerField(default=0, verbose_name="总访问量")
    unique_visitors = models.IntegerField(default=0, verbose_name="唯一访客数")
    unique_ips = models.IntegerField(default=0, verbose_name="唯一IP数")
    # most_visited_path = models.CharField(max_length=200, blank=True, null=True, verbose_name="最热门路径")
    # visits_by_hour = models.JSONField(default=dict, verbose_name="按小时访问分布")
    
    class Meta:
        verbose_name = "访问统计摘要"
        verbose_name_plural = "访问统计摘要"
    

MyWeb/MyBlog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author','email','body']
        widgets = {
            'author':forms.TextInput(attrs={'class':'form-control','placeholder':'请输入你的名称'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'请输入邮箱(不会公开)','required': False}),
            'body':forms.Textarea(attrs={'class':'form-control','rows':4,'placeholder':'请输入评论内容'}),
        }
        labels = {
            'author':'昵称',
            'email':'邮箱',
            'body':'评论内容',
        }

MyWeb/MyBlog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.views import generic
from .models import *
from django.db.models import Count,Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .forms import CommentForm
from django.db.models.functions import TruncMonth

# ===================基础样式=================================================
# class IndexView(generic.ListView):
#     """
#         首页
#     """
#     model = Article
#     template_name = "blog/home.html"
#     def get_queryset(self):
#         """Return the last five published questions."""
#         return Article.objects.all()

# class ArticleDetailView(generic.DetailView):
#     """文章内容"""
#     model = Article
#     template_name = "blog/article_detail.html"
# =============================文章列表=======================================

def article_list(request):
    articles = Article.objects.all().order_by('-pub_date').prefetch_related('tags')
    paginator = Paginator(articles,8)
    page = request.GET.get('page')
    
    try:
        article_page = paginator.page(page)
    except PageNotAnInteger:
        article_page = paginator.page(1)
    except EmptyPage:
        article_page = paginator.page(paginator.num_pages)
    

    context = {
        'articles':article_page,
    }
    return render(request,'blog/article_list.html',context)
# ================================标签分类跳转页=========================================
class ArriveAtView(generic.ListView):
    model = Article
    context_object_name = 'articles'
    template_name = 'blog/arrived.html'
    paginate_by = 8
    
    def is_request_tag(self):
        
        return self.request.path.startswith('/MyBlog/archive/tag/')
    
    def is_request_cate(self):

        return self.request.path.startswith('/MyBlog/archive/category/')
    
    def get_queryset(self):
        
        # print("请求路径:", self.request.path)
        # print("URL参数:", self.kwargs)
        tag_slug = self.kwargs.get('tag_slug')
        cat_slug = self.kwargs.get('cat_slug')

        if self.is_request_tag() and tag_slug:

            tag = get_object_or_404(ArticleTag, slug=tag_slug)
            self.current_filter = 'tag'
            self.current_slug = tag_slug
            
            return Article.objects.filter(tags=tag).prefetch_related('tags', 'category')
        
        elif self.is_request_cate() and cat_slug:

            category = get_object_or_404(Category, slug=cat_slug)
            
            self.current_filter = 'category'
            self.current_slug = cat_slug
            return Article.objects.filter(category=category).prefetch_related('tags', 'category')
        
        else:
            
            return Article.objects.none()
        
    
    def get_context_data(self, **kwargs):
        
        
        context = super().get_context_data(**kwargs)
        if hasattr(self,'current_filter'):
            if self.current_filter == 'tag':
                context['current_task'] = get_object_or_404(ArticleTag,slug=self.current_slug)
            elif self.current_filter == 'category':
                context['current_task'] = get_object_or_404(Category,slug=self.current_slug)

        return context

# =====================================评论视图===============================================
def commentview(request,pk):

    article = get_object_or_404(Article,pk=pk)
    article.increase_visited(request)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            # 不做重定向的话，页面会重复提交表单且跳转到页面顶部
            return redirect(f'{request.path}#comment-section')
    else:
        form = CommentForm()

    comments = article.comments.all()
    total_cmt = comments.count()
    for i,cmt in enumerate(comments,start=1):
        cmt.floor = total_cmt - i + 1

    context = {
        'article': article,
        'comments': comments,
        'form': form,
    }
    
    return render(request, 'blog/article_detail.html', context)
# =======================================搜索==================================================
class SearchView(generic.ListView):

    model = Article
    template_name = "blog/search.html"
    context_object_name = "articles"
    paginate_by = 8

    def get_queryset(self):

        query = self.request.GET.get('q','')
        if query:

            return Article.objects.filter(
                Q(title__icontains=query) |
                Q(overview__icontains=query) |
                Q(raw_content__icontains=query)
            ).distinct().order_by('-pub_date')
        
        return Article.objects.none()
    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q','')

        return context
# =======================================归档======================================================

class ArchiveView(generic.ListView):
    model = Article
    template_name = "blog/archive.html"
    context_object_name = "archive_data"

    def get_queryset(self):
        
        articles = Article.objects.order_by('-pub_date')
        
        year_month_data = {}
        
        for article in articles:
            pub_date = article.pub_date
            year = pub_date.year
            month = pub_date.month
            
           
            if year not in year_month_data:
                year_month_data[year] = {}
            
            
            if month not in year_month_data[year]:
                year_month_data[year][month] = []
            
            
            year_month_data[year][month].append(article)
        
       
        archive_data = []
        for year in sorted(year_month_data.keys(), reverse=True):
            year_articles = year_month_data[year]
            year_total = 0
            month_list = []
            
            for month in sorted(year_articles.keys(), reverse=True):
                month_articles = year_articles[month]
                month_total = len(month_articles)
                year_total += month_total
                
                month_list.append({
                    'month': month,
                    'articles': month_articles,
                    'ycount': month_total
                })
            
            archive_data.append({
                'year': year,
                'months': month_list,
                'total_count': year_total
            })
        
        return archive_data
    
# =======================================关于======================================================

class AboutDetailView(generic.DetailView):
    """关于我们"""
    model = About
    slug_field = "slug"  
    slug_url_kwarg = "slug" 
    template_name = "blog/about.html"


# ==========================================================================================

MyWeb/MyBlog/templates/blog/archive.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}归档{% endblock %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'MyBlog/css/archive.css' %}">
{% endblock %}

{% block content %}
<div class="archive-container">
    {% for year_data in archive_data %}
    <div class="archive-header">
            <div class="archive-date year">{{ year_data.year }}</div>
            <div class="archive-icon icon-header"></div>
            <div class="archive-title total-article">{{ year_data.total_count }}篇文章</div>
    </div>
        {% for months_data in year_data.months %}
            {% for article in months_data.articles %}
            <a class="pub-data" href="{% url 'MyBlog:article_detail' article.id %}">
                <div class="archive-date day">{{ article.pub_date|date:"m-d" }}</div>
                <div class="archive-icon icon-body"></div>
                <div class="archive-title article-title">{{ article.title }}</div>
            </a>
            {% endfor %}
        {% endfor %}
    {% endfor %}
</div>
{% endblock content %}

MyWeb/MyBlog/templates/blog/arrived.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}文章列表-第{{ article.number }}页{% endblock %}

<!--添加css-->
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'MyBlog/css/blog.css' %}">
{% endblock %}

<!--主要内容-->
{% block content %}
<div class="article-list-container">

    {% for article in articles %}
    <article class="article-card">
        {% if article.cover_img %}
        <div class="article-cover">
            <img src="{{ article.cover_img.url }}" alt="{{ article.title }}封面" class="cover-image">
        </div>
        {% endif %}
        <div class="article-info">
            <div class="card-title">
                <i class="card-icon"></i>
                <h2 class="list-title">
                    <a href="{% url 'MyBlog:article_detail' article.id %}">{{ article.title }}</a>
                </h2>
            </div>
            <div class="meta-info">

                <div class="meta-section card-date">
                    <div class="meta-icon date-icon">
                        <img src="{% static 'MyBlog/css/imgs/icons/calendar.png'%}" alt="date-icon" class="date-icon">
                    </div>
                    <span class="pub-date">{{ article.pub_date|date:"Y-m-d" }}</span>
                </div>

                {% if article.category %}
                <div class="meta-section card-category">
                    <div class="meta-icon category-icon" >
                        <img src="{% static 'MyBlog/css/imgs/icons/computer.png'%}" alt="category-icon" class="category-icon">
                    </div>
                    <span class="article-category-name">{{ article.category }}</span>
                </div>
                {% endif %}

                {% if article.tags.exists %}
                <div class="meta-section card-tag">
                    <div class="meta-icon ">
                        <img src="{% static 'MyBlog/css/imgs/icons/井.png'%}" alt="tag-icon" class="tag-icon">
                    </div>
                    {% for tag in article.tags.all %}
                    <span class="tag-name">{{ tag.name }}{% if not forloop.last %}/{% endif %}</span>
                    {% endfor %}
                </div>
                {% endif %}

            </div>
            <div class="card-overview">概述：{{ article.overview }}</div>
            <div class="card-count">
                <span class="word_count">字数：{{ article.word_count }}</span>
                <span class="visitor_count">| 访问：{{ article.visited_num }}</span>
            </div>
        </div>
 
    </article>
    {% empty %}
    <div class="empty-tip">
        <p>暂时还没有发布文章哦~</p>
    </div>
    
{% endfor %}

</div>
<!--分页控制-->
<div class="pagination-container">
    <div class="pagination">
        {% if articles.has_previous %}
        <a href="?page=1" class="pagination-link first-page" title="第一页">
            
            <img src="{% static 'MyBlog/css/imgs/icons/angle2_left.png' %}" class="angle2-left">
        </a>
        <a href="?page={{ articles.previous_page_number }}" class="pagination-link pre-page" title="上一页">
            
            <img src="{% static 'MyBlog/css/imgs/icons/angle_left.png' %}" class="angle-left">
        </a>
        {% else %}
            <span class="pagination-link disabled">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle2_left.png' %}" class="angle2-left">
            </span>
                <span class="pagination-link disabled">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle_left.png' %}" class="angle-left">
            </span>
        {% endif %}
        <div class="page-number">
            {% for num in articles.paginator.page_range %}
                {% if num == articles.number %}
                    <span class="pagination-link current-page">{{ num }}</span>
                {% elif num > articles.number|add:'-3' and num < articles.number|add:'3' %}
                    <a href="?page={{ num }}" class="pagination-link">{{ num }}</a>
                {% elif num == 1 or num == articles.paginator.num_pages %}
                    <a href="?page={{ num }}" class="pagination-link">{{ num }}</a>
                {% elif num == articles.number|add:'-4' or num == articles.number|add:'4' %}
                    <span class="pagination-ellipsis">...</span>
                {% endif %}
            {% endfor%}
        </div>
        {% if articles.has_next %}
            <a href="?page={{ articles.next_page_number }}" class="pagination-link next_page" title="下一页">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle_right.png' %}" class="angle-right">
            </a>
            <a href="?page={{ articles.paginator.num_pages }}" class="pagination-link last-page" title="最后一页">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle2_right.png' %}" class="angle2-right">
            </a>
        {% else %}
            <span class="pagination-link disabled">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle_right.png' %}" class="angle-right">
            </span>
            <span class="pagination-link disabled">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle2_right.png' %}" class="angle2-right">
            </span>
        {% endif %}
    </div>
    <div class="pagination-info">
        第 {{ articles.number }} 页，共 {{ articles.paginator.num_pages }} 页
    </div>
</div>

{% endblock %}

MyWeb/MyBlog/templates/blog/article_detail.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}{{ article.title }} - 我的博客{% endblock title %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'MyBlog/css/article_detail.css' %}">
<link rel="stylesheet" href="{% static 'MyBlog/css/pygments.css' %}">
{% endblock extrastyle %}

{% block content %}

<article class="article-content">
    <header>
        <h2 class="title">{{ article.title }}</h2>
        <div class="meta">
            <span class="pub-date">发布日期：{{ article.pub_date|date:"Y-m-d" }}</span>
            <span class="version">评论数：{{ article.comments.count }}</span>
        </div>
    </header>
    
    <section class="content">
        {{ article.rendered_content|safe }}
    </section>
</article>
<!-------------------------------------------------------------------------------------评论模块-->
<div class="comment-section" id="comment-section">

    <!---提交评论-->
    <div class="comment-body">
        <h3 class="comment-section-title">发表评论</h3>
        <form class="comment-input" method="post" >
            {% csrf_token %}
            <div class="comment-section-header">
                
                <div class="comment-section-author">
                    <label for="{{ form.author.id_for_label}}">{{ form.author.label }}</label>
                    {{ form.author }}
                </div>

                <div class="comment-section-email">
                    <label for="{{ form.email.id_for_label}}">{{ form.email.label }}</label>
                    {{ form.email }}
                </div>

            </div>

            <div class="comment-section-body">
                    <label for="{{ form.body.id_for_label}}">{{ form.body.label }}</label>
                    {{ form.body }}
            </div>

            <input type="submit" class="comment-submit" value="发送">
        </form>
    </div>
<!--评论区-->
    <div class="comment-list">
        <h3 class="comment-list-title">{{ article.comments.count }}条评论</h3>
        {% for cmt in comments %}
        <div class="comment-container">
            <div class="comment-list-header">
                <div class="comment-user">{{ cmt.author }} ({{ cmt.comment_date|date:"Y-m-d H:i" }})</div>
                <div class="floor">#{{ cmt.floor }}楼</div>
            </div>
            
            <div class="comment-content">{{ cmt.body }}</div>
            
        </div>
        {% empty %}
        <div class="empty-comment">暂无评论</div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

MyWeb/MyBlog/templates/blog/article_list.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}文章列表-第{{ article.number }}页{% endblock %}

<!--添加css-->
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'MyBlog/css/blog.css' %}">
{% endblock %}

<!--主要内容-->
{% block content %}
<div class="article-list-container">

    {% for article in articles %}
    <article class="article-card">
        {% if article.cover_img %}
        <div class="article-cover">
            <img src="{{ article.cover_img.url }}" alt="{{ article.title }}封面" class="cover-image">
        </div>
        {% endif %}
        <div class="article-info">
            <div class="card-title">
                <i class="card-icon"></i>
                <h2 class="list-title">
                    <a href="{% url 'MyBlog:article_detail' article.id %}">{{ article.title }}</a>
                </h2>
            </div>
            <div class="meta-info">

                <div class="meta-section card-date">
                    <div class="meta-icon date-icon">
                        <img src="{% static 'MyBlog/css/imgs/icons/calendar.png'%}" alt="date-icon" class="date-icon">
                    </div>
                    <span class="pub-date">{{ article.pub_date|date:"Y-m-d" }}</span>
                </div>

                {% if article.category %}
                <div class="meta-section card-category">
                    <div class="meta-icon category-icon" >
                        <img src="{% static 'MyBlog/css/imgs/icons/computer.png'%}" alt="category-icon" class="category-icon">
                    </div>
                    <span class="article-category-name">{{ article.category }}</span>
                </div>
                {% endif %}

                {% if article.tags.exists %}
                <div class="meta-section card-tag">
                    <div class="meta-icon ">
                        <img src="{% static 'MyBlog/css/imgs/icons/井.png'%}" alt="tag-icon" class="tag-icon">
                    </div>
                    {% for tag in article.tags.all %}
                    <span class="tag-name">{{ tag.name }}{% if not forloop.last %}/{% endif %}</span>
                    {% endfor %}
                </div>
                {% endif %}

            </div>
            <div class="card-overview">概述：{{ article.overview }}</div>
            <div class="card-count">
                <span class="word_count">字数：{{ article.word_count }}</span>
                <span class="visitor_count">| 访问：{{ article.visited_num }}</span>
            </div>
        </div>
 
    </article>
    {% empty %}
    <div class="empty-tip">
        <p>暂时还没有发布文章哦~</p>
    </div>
    
{% endfor %}

</div>
<!--分页控制-->
<div class="pagination-container">
    <div class="pagination">
        {% if articles.has_previous %}
        <a href="?page=1" class="pagination-link first-page" title="第一页">
            
            <img src="{% static 'MyBlog/css/imgs/icons/angle2_left.png' %}" class="angle2-left">
        </a>
        <a href="?page={{ articles.previous_page_number }}" class="pagination-link pre-page" title="上一页">
            
            <img src="{% static 'MyBlog/css/imgs/icons/angle_left.png' %}" class="angle-left">
        </a>
        {% else %}
            <span class="pagination-link disabled">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle2_left.png' %}" class="angle2-left">
            </span>
                <span class="pagination-link disabled">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle_left.png' %}" class="angle-left">
            </span>
        {% endif %}
        <div class="page-number">
            {% for num in articles.paginator.page_range %}
                {% if num == articles.number %}
                    <span class="pagination-link current-page">{{ num }}</span>
                {% elif num > articles.number|add:'-3' and num < articles.number|add:'3' %}
                    <a href="?page={{ num }}" class="pagination-link">{{ num }}</a>
                {% elif num == 1 or num == articles.paginator.num_pages %}
                    <a href="?page={{ num }}" class="pagination-link">{{ num }}</a>
                {% elif num == articles.number|add:'-4' or num == articles.number|add:'4' %}
                    <span class="pagination-ellipsis">...</span>
                {% endif %}
            {% endfor%}
        </div>
        {% if articles.has_next %}
            <a href="?page={{ articles.next_page_number }}" class="pagination-link next_page" title="下一页">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle_right.png' %}" class="angle-right">
            </a>
            <a href="?page={{ articles.paginator.num_pages }}" class="pagination-link last-page" title="最后一页">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle2_right.png' %}" class="angle2-right">
            </a>
        {% else %}
            <span class="pagination-link disabled">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle_right.png' %}" class="angle-right">
            </span>
            <span class="pagination-link disabled">
                
                <img src="{% static 'MyBlog/css/imgs/icons/angle2_right.png' %}" class="angle2-right">
            </span>
        {% endif %}
    </div>
    <div class="pagination-info">
        第 {{ articles.number }} 页，共 {{ articles.paginator.num_pages }} 页
    </div>
</div>

{% endblock %}

MyWeb/MyBlog/templates/blog/home.html
{% extends 'base/base.html' %}